# Generated by Django 4.0.6 on 2023-01-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاور'},
        ),
    ]
